In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [1]:
import torch

# Check the installed version
print(torch.__version__)

# Check if a GPU is available for hardware acceleration
print(torch.cuda.is_available())

2.10.0+cu128
True


In [2]:
import numpy as np

# Creating tensors of varying dimensions
tensor0d = torch.tensor(1) # Scalar
tensor1d = torch.tensor([1, 2, 3]) # Vector
tensor2d = torch.tensor([[1, 2], [3, 4]]) # Matrix
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D Tensor

# Interfacing with NumPy
ary3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

tensor3d_2 = torch.tensor(ary3d)      # Creates a new copy of the data
tensor3d_3 = torch.from_numpy(ary3d)  # Shares memory with the original array

# Modifying the original NumPy array to prove memory sharing
ary3d[0, 0, 0] = 999
print(tensor3d_2) # Remains unchanged (it was a copy)
print(tensor3d_3) # Changes to 999 (it shares memory)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


In [7]:
import torch
import torch.nn as nn

# ---------------------------------------------------------
# STEP 1: The Data
# ---------------------------------------------------------
# Input data (X) and the true answers (Y)
# The hidden rule we want the model to learn is simply: Y = X * 2
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
Y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])

# ---------------------------------------------------------
# STEP 2: The Model and The Robot Assistant
# ---------------------------------------------------------
# We create a simple model with 1 input and 1 output (just 1 weight and 1 bias)
model = nn.Linear(in_features=1, out_features=1)

# We hire our Robot Assistant (Optimizer) and give it the keys to the model's dials
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# We define how we will measure our Error (Mean Squared Error)
loss_function = nn.MSELoss()

# ---------------------------------------------------------
# STEP 3: The Training Loop (Practicing 50 times)
# ---------------------------------------------------------
epochs = 500

for epoch in range(epochs):
    
    # Action A: Make a prediction (Play the soundboard)
    predictions = model(X)
    
    # Action B: Calculate the Error (How bad does the music sound?)
    loss = loss_function(predictions, Y)
    
    # Action C: Throw away old sticky notes from the previous loop!
    optimizer.zero_grad()
    
    # Action D: Do calculus and print new sticky notes (Gradients)
    loss.backward()
    
    # Action E: The Robot Assistant reads the notes and updates the dials!
    optimizer.step()
    
    # Print the progress every 10 steps so we can watch it learn
    if (epoch + 1) % 10 == 0:
        print(f"Practice Round {epoch + 1} | Error (Loss): {loss.item():.4f}")

# ---------------------------------------------------------
# STEP 4: The Final Test
# ---------------------------------------------------------
print("\n--- Training Complete! ---")

# Let's ask it to predict a number it has NEVER seen before: 10.0
test_number = torch.tensor([[10.0]])

# Turn off the calculus engine since we are just testing, not training
with torch.no_grad():
    final_guess = model(test_number)

print(f"If the input is 10.0, the model guesses: {final_guess.item():.4f}")
print("(The perfect answer would be 20.0)")

Practice Round 10 | Error (Loss): 0.7023
Practice Round 20 | Error (Loss): 0.2239
Practice Round 30 | Error (Loss): 0.1995
Practice Round 40 | Error (Loss): 0.1876
Practice Round 50 | Error (Loss): 0.1767
Practice Round 60 | Error (Loss): 0.1664
Practice Round 70 | Error (Loss): 0.1567
Practice Round 80 | Error (Loss): 0.1476
Practice Round 90 | Error (Loss): 0.1390
Practice Round 100 | Error (Loss): 0.1309
Practice Round 110 | Error (Loss): 0.1233
Practice Round 120 | Error (Loss): 0.1161
Practice Round 130 | Error (Loss): 0.1094
Practice Round 140 | Error (Loss): 0.1030
Practice Round 150 | Error (Loss): 0.0970
Practice Round 160 | Error (Loss): 0.0913
Practice Round 170 | Error (Loss): 0.0860
Practice Round 180 | Error (Loss): 0.0810
Practice Round 190 | Error (Loss): 0.0763
Practice Round 200 | Error (Loss): 0.0719
Practice Round 210 | Error (Loss): 0.0677
Practice Round 220 | Error (Loss): 0.0637
Practice Round 230 | Error (Loss): 0.0600
Practice Round 240 | Error (Loss): 0.0565
P

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------------------------------------------
# STEP 1: The Data
# X = [x_coordinate, y_coordinate]
# Y = Category (0 is Red, 1 is Blue)
# ---------------------------------------------------------
X_train = torch.tensor([
    [-1.2, 3.1], [-0.9, 2.9], [-0.5, 2.6], # These are Red dots (0)
    [ 2.3,-1.1], [ 2.7,-1.5]               # These are Blue dots (1)
])
y_train = torch.tensor([0, 0, 0, 1, 1])

# ---------------------------------------------------------
# STEP 2: The Model and Robot Assistant
# ---------------------------------------------------------
# 2 inputs (x, y coordinates) -> 2 outputs (Red score, Blue score)
model = nn.Linear(in_features=2, out_features=2) 

optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

# ---------------------------------------------------------
# STEP 3: The 5-Step Training Loop
# ---------------------------------------------------------
epochs = 3

for epoch in range(epochs):
    
    # 1. Predict (Outputs 2 scores for every dot)
    logits = model(X_train)
    
    # 2. Calculate Error using Cross Entropy
    loss = F.cross_entropy(logits, y_train)
    
    # 3. Trash old sticky notes
    optimizer.zero_grad()
    
    # 4. Print new sticky notes
    loss.backward()
    
    # 5. Robot twists the dials
    optimizer.step()
    
    print(f"Epoch: {epoch+1:03d}/{epochs:03d} | Error: {loss.item():.2f}")

# ---------------------------------------------------------
# STEP 4: Evaluating the Model (Did it actually learn?)
# ---------------------------------------------------------
print("\n--- Let's see its final predictions! ---")

with torch.no_grad():
    raw_scores = model(X_train)

# Softmax turns the raw scores into percentages (0% to 100%)
probabilities = torch.softmax(raw_scores, dim=1)
print("Probabilities (Red% vs Blue%):\n", probabilities)

# Argmax picks the category with the highest percentage
predictions = torch.argmax(probabilities, dim=1)
print("\nModel's Final Guesses:", predictions)
print("The True Answers were:  ", y_train)

# Calculate Accuracy
correct_guesses = torch.sum(predictions == y_train)
print(f"\nAccuracy: {correct_guesses.item()} / 5 correct!")

Epoch: 001/003 | Error: 0.01
Epoch: 002/003 | Error: 0.01
Epoch: 003/003 | Error: 0.01

--- Let's see its final predictions! ---
Probabilities (Red% vs Blue%):
 tensor([[0.9961, 0.0039],
        [0.9926, 0.0074],
        [0.9820, 0.0180],
        [0.0142, 0.9858],
        [0.0052, 0.9948]])

Model's Final Guesses: tensor([0, 0, 0, 1, 1])
The True Answers were:   tensor([0, 0, 0, 1, 1])

Accuracy: 5 / 5 correct!


In [9]:
import torch

# 1. Check if a GPU is plugged in and available
if torch.cuda.is_available():
    device = torch.device("cuda") # CUDA is Nvidia's GPU software
    print("GPU found! Get ready for hyperspeed.")
else:
    device = torch.device("cpu")
    print("No GPU found. Sticking with the CPU.")

# 2. Move your Model to the GPU
model = model.to(device)

# 3. Move your Data to the GPU (Do this inside your training loop!)
X_train = X_train.to(device)
y_train = y_train.to(device)

GPU found! Get ready for hyperspeed.
